import { Room, TimeSlot, UserSession } from '../types';

export const TIME_SLOTS: TimeSlot[] = [
  '07:30 - 09:30',
  '09:30 - 11:30',
  '13:00 - 15:00',
  '15:00 - 17:00',
];

export const BUILDINGS = ['A', 'B', 'C', 'V'] as const;

export const EQUIPMENT_OPTIONS = [
  'Projector',
  'Whiteboard',
  'High-spec PC',
  'AC',
] as const;

export const DEFAULT_USER_SESSION: UserSession = {
  id: 'usr-vku-001',
  name: 'Tran Huu Long',
  studentId: '21IT089',
  email: 'longth.21it@vku.udn.vn',
  faculty: 'Information Technology & Digital Economy',
};

export const MOCK_ROOMS: Room[] = [
  {
    id: 'room-a-201',
    name: 'Smart Lab A201',
    image_url: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
    building: 'A',
    floor: 2,
    capacity: 12,
    equipment: ['High-spec PC', 'Projector', 'AC', 'Whiteboard'],
    status: 'Available Now',
    description: 'Specialized lab equipped with dual-monitor workstations for software engineering & AI projects.',
  },
  {
    id: 'room-a-305',
    name: 'Innovation Hub A305',
    image_url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=80',
    building: 'A',
    floor: 3,
    capacity: 8,
    equipment: ['Projector', 'Whiteboard', 'AC'],
    status: 'Available Now',
    description: 'Designed for agile sprint planning and brainstorming sessions with interactive whiteboard.',
  },
  {
    id: 'room-b-102',
    name: 'Co-working Studio B102',
    image_url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=800&q=80',
    building: 'B',
    floor: 1,
    capacity: 16,
    equipment: ['Projector', 'Whiteboard', 'AC'],
    status: 'Occupied',
    description: 'Spacious collaborative space on the ground floor with modular tables and presentation tools.',
  },
  {
    id: 'room-b-404',
    name: 'Focus Pod B404',
    image_url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=80',
    building: 'B',
    floor: 4,
    capacity: 4,
    equipment: ['Whiteboard', 'AC'],
    status: 'Available Now',
    description: 'Quiet room ideal for focused research groups, code reviews, and pair programming.',
  },
  {
    id: 'room-c-203',
    name: 'Creative Room C203',
    image_url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    building: 'C',
    floor: 2,
    capacity: 6,
    equipment: ['Projector', 'AC'],
    status: 'Available Now',
    description: 'Ergonomic seating with natural lighting, perfect for digital design and multimedia presentations.',
  },
  {
    id: 'room-c-501',
    name: 'Executive Boardroom C501',
    image_url: 'https://images.unsplash.com/photo-1505409859467-3a796fd5798e?auto=format&fit=crop&w=800&q=80',
    building: 'C',
    floor: 5,
    capacity: 20,
    equipment: ['Projector', 'Whiteboard', 'High-spec PC', 'AC'],
    status: 'Available Now',
    description: 'Full-capacity seminar and capstone defense room with surround audio and 4K projection.',
  },
  {
    id: 'room-v-101',
    name: 'Korea-Vietnam Center V101',
    image_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    building: 'V',
    floor: 1,
    capacity: 10,
    equipment: ['High-spec PC', 'AC', 'Whiteboard'],
    status: 'Occupied',
    description: 'High-tech collaboration zone sponsored by KOICA for international student exchange & hackathons.',
  },
  {
    id: 'room-v-302',
    name: 'VR & Game Lab V302',
    image_url: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80',
    building: 'V',
    floor: 3,
    capacity: 14,
    equipment: ['High-spec PC', 'Projector', 'AC'],
    status: 'Available Now',
    description: 'Equipped with RTX workstations for game development, computer graphics, and VR testing.',
  },
  {
    id: 'room-a-108',
    name: 'Quick Huddle A108',
    image_url: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=80',
    building: 'A',
    floor: 1,
    capacity: 2,
    equipment: ['AC', 'Whiteboard'],
    status: 'Available Now',
    description: 'Compact 2-person study nook for one-on-one tutoring or quiet thesis prep.',
  },
  {
    id: 'room-b-301',
    name: 'Data Science Lab B301',
    image_url: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=800&q=80',
    building: 'B',
    floor: 3,
    capacity: 18,
    equipment: ['High-spec PC', 'Projector', 'Whiteboard', 'AC'],
    status: 'Occupied',
    description: 'High computing power setup for big data processing, ML model training, and data workshops.',
  },
];

